---
name: Distrobuilder build lxd image container
description: Build lxd image container
inputs:
  repo:
    description: repo
    default: ${{ github.action.repository }}
    required: true

runs:
  using: composite
  steps:
    - name: run image builder
      shell: bash
      run: |
        docker run \
          --rm \
          --privileged \
          --volume ${{ github.workspace }}:/data \
          ghcr.io/${{ github.inputs.command }}
