---
name: Distrobuilder build lxd image container
description: Build lxd image container
inputs:
  registry:
    description: Registry to use for pull container
    default: ghcr.io
    required: true
  image:
    description: Image to use for build
    default: ${{ github.action_repository }}
    required: true
  data:
    description: Directory with the config files
    default: ${{ github.workspace }}
    required: true


runs:
  using: composite
  steps:
    - name: Run image builder
      shell: bash
      run: |
        docker run \
          --rm \
          --privileged \
          --volume ${{ inputs.data }}:/data \
          ${{ inputs.registry }}/${{ inputs.image }}
