---
name: Build and push container image

on:
  #push:
  #  branches:
  #  - main
  #  - master
  workflow_dispatch:

jobs:
  build-and-push-image:
    name: Build and push container image
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_TAGS: ${{ github.sha }} latest
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      REGISTRY_USER: ${{ github.repository_owner }}
      REGISTRY_PASSWORD: ${{ github.token }}

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.event.repository.name }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # minimal (short sha)
            type=sha
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
