---
name: Build and push container image

on:
  #push:
  #  branches:
  #  - main
  #  - master
  workflow_dispatch:

jobs:
  build-and-push-image:
    name: Build and push container image
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_TAGS: latest ${{ github.sha }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      REGISTRY_USER: ${{ github.repository_owner }}
      REGISTRY_PASSWORD: ${{ github.token }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - run: |
          echo ${{ github.action_repository }}
          echo ${{ github.action.repository }}
    
      # Build image using Buildah action
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./Dockerfile
    
      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push to ghrc
        id: push-to-ghrc
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
  
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-ghrc.outputs.registry-paths }}"

      #- name: Build and push container image
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: .
      #    push: true
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}
