---
name: test

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    name: test
    runs-on: ubuntu-22.04

    steps:
    
      - run: |
          echo ${{ github.action_repository }}
          echo ${{ github.action.repository }}
          echo $GITHUB_ACTION_REPOSITORY
          env
